### ISSUE TITLE
Scrolling of the preview

### ISSUE THREAD

**Issue by hakimio** [alagrede/znote-app#30]
Few preview scrolling issues I have noticed:
- you can scroll the preview with mouse wheel independently from editing area but the preview scrollbar is not visible
- the bottom of the preview seems to be "cut-off". It would be nice if there was a bit of empty space between the bottom of the preview and the bottom toolbar.

![cut-off preview](https://user-images.githubusercontent.com/768105/124273712-a9514e80-db40-11eb-8072-de9fd0a51a5d.PNG)

- Editing area scrolling is linked to preview scrolling. I don't think that's a good idea because in a lot of cases editing area and preview will have different heights and the scrolling positions will not match exactly. Imho, the preview should scroll automatically to the bottom when you add text to the editing area but otherwise the editing and preview scrollbars should be independent.

OT: it would be nice if there was an option to hide "tag" side panel without hiding note selection panel.

**Comment by alagrede** [comment]
Hello @hakimio,

Thank you for taking the time to explain me your problem. The scroll with the preview is a very sensitive topic and I already tested lot of things... 😅
I already allow scrolling the preview with the mouse to adjust the preview with the editor and force to keep the base position when editing (because you're right, the edit area and the preview will often have different heights). So it is a voluntary behavior. I am open to any others proposals. 
=> Maybe an option to quickly stop the dependent scrolling it's a good idea. Personally this actual behavior suits me but I can of course complete.

Ok to add an empty space at the end of the preview. It should be nice 👍

For your Other Thing, I totally agree with you ✨, it might be nice to hide the left tag / project panel without hiding the note selection panel. I'm already working on it. I'm also investigating the possibility to add open notes tabs.

I will make proposals soon HERE before release these features.

Thank you for your contact
Cheers,
Anthony

**Comment by hakimio** [comment]
Hi @alagrede 

Thinking about it a bit more, I don't really mind linked scrolling. I just find it strange that you can't see preview scrollbar. You could also make linked scrolling optional, but it doesn't have to be high priority.

Thank you for looking into all the feature requests and making this awesome app :)

**Comment by hakimio** [comment]
@alagrede Looks good. Just hopefully people will  understand what the scrollbar icon does (maybe it should be slightly bigger to make it easier to click on it?).
BTW, does it remember side panel state when you restart the app?

**Comment by alagrede** [comment]
Yes 👍 the state of side panel state is persisted when you restart the app.
I also update a bit the scroll icon. I think it's ok for a first version of this feature.

Thank you for your help 🙏
I will release the 0.7.11 maybe tonight or tomorrow morning.

**Comment by hakimio** [comment]
@alagrede is there a way to move existing notes to a newly created project? Also, maybe the icon next to "All notes" should be a "plus" instead of a "minus" or there should just be one big button above "All notes" saying "Add a notebook"? I think right now it's not really obvious how to add new notebooks by just looking at the UI.

**Comment by alagrede** [comment]
Hi, I changed this to a "plus icon" to be a bit clearer.
Regarding moving existing notes, I created a dedicated number here: https://github.com/alagrede/znote-app/issues/32

Thank you

**Comment by hakimio** [comment]
Thanks. Here are few other usability enhancements that might be needed:
- When you focus "Notebook name" field, the label becomes impossible to read due to low contrast (at least in dark mode).
- Might be nice to have "Cancel" and "Add" buttons on the bottom toolbar of "Add Notebook" dialog. Close icon button on title bar might be a good idea as well.
- `Path: >root` looks really strange. Maybe it should just be `Path: root`?

Concerning moving of multiple tasks to different notebook: at first I just didn't see that you can change note's notebook at all. Having ability to select and move multiple notes might be nice but no need to prioritize it. Instead it would be nice to have a notebook rename/edit feature.
